/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ex13;

/**
 *
 * @author Aluno
 */
public class tela_to_to_list extends javax.swing.JPanel {

    /**
     * Creates new form tela_to_to_list
     */
    public tela_to_to_list() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jTextFielddescricaotarefa = new javax.swing.JTextField();
        jButtonadicionartarefa = new javax.swing.JButton();
        jComboBoxfiltostatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletarefas = new javax.swing.JTable();
        jButtonconcluirtarefas = new javax.swing.JButton();
        jButtonremovertarefas = new javax.swing.JButton();

        jButtonadicionartarefa.setText("adicionar");
        jButtonadicionartarefa.addActionListener(this::jButtonadicionartarefaActionPerformed);

        jComboBoxfiltostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "todos", "concluido", "não concluido" }));
        jComboBoxfiltostatus.addActionListener(this::jComboBoxfiltostatusActionPerformed);

        jTabletarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "tarefa", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabletarefas);

        jButtonconcluirtarefas.setText("concluir");
        jButtonconcluirtarefas.addActionListener(this::jButtonconcluirtarefasActionPerformed);

        jButtonremovertarefas.setText("remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFielddescricaotarefa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonadicionartarefa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxfiltostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonconcluirtarefas)
                                .addGap(55, 55, 55)
                                .addComponent(jButtonremovertarefas)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFielddescricaotarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonadicionartarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxfiltostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonconcluirtarefas)
                    .addComponent(jButtonremovertarefas))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonadicionartarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonadicionartarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonadicionartarefaActionPerformed

    private void jComboBoxfiltostatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxfiltostatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxfiltostatusActionPerformed

    private void jButtonconcluirtarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconcluirtarefasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonconcluirtarefasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadicionartarefa;
    private javax.swing.JButton jButtonconcluirtarefas;
    private javax.swing.JButton jButtonremovertarefas;
    private javax.swing.JComboBox<String> jComboBoxfiltostatus;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletarefas;
    private javax.swing.JTextField jTextFielddescricaotarefa;
    // End of variables declaration//GEN-END:variables
}
